### ISSUE TITLE
邀请收录进： awesome-github-profile-readme-chinese

### ISSUE THREAD

**Issue by eryajf** [hugh-zhan9/LeetCodePractice#1]
你好，你的个人主页 https://github.com/hugh-zhan9 很赞，我做了一个中文区优秀个人主页合集的项目，特邀请你参与贡献。

项目地址：https://github.com/eryajf/awesome-github-profile-readme-chinese

因为个人主页项目关闭了issue，因此来到这里提了，见谅

**Comment by hugh-zhan9** [comment]
> 你好，你的个人主页 https://github.com/hugh-zhan9 很赞，我做了一个中文区优秀个人主页合集的项目，特邀请你参与贡献。
> 
> 项目地址：https://github.com/eryajf/awesome-github-profile-readme-chinese
> 
> 因为个人主页项目关闭了issue，因此来到这里提了，见谅

你好我已提交 pr ，谢谢你的邀请
